[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
station_iapetus = { path = "../game", default-features = false }

[features]
default = ["station_iapetus/default"]
dylib-engine = ["station_iapetus/dylib-engine"]
