[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
station_iapetus = { path = "../game", optional = true }

[features]
default = ["station_iapetus"]
dylib = ["fyrox/dylib"]
